= Custom Loader

Developer can integrate custom loader by adding code in native(iOS/android).

Custom loader is integrated in starter application:

* iOS: link:../ios/Loader[here]
* android: link:../android/app/src/customloader[here]

== Modifications:

* Developer can change assets of loader by modifying it.
To modify custom loader please refer respective https://github.com/ostdotcom/ost-wallet-sdk-ios/blob/release-2.4/Samples/CustomLoader/OstMockCustomLoader.md#customize-loader[iOS] and https://github.com/ostdotcom/ost-wallet-sdk-android/blob/release-2.4/Samples/customloader/OstCustomLoader.md#customize-loader[android] readme.
+ (For iOS) size for loader can be modify by changing link:../ios/Loader/OstMockLoaderViewController.swift#L197[width] and link:../ios/Loader/OstMockLoaderViewController.swift#L198[height].
current value is `30 pt`.
* To modify error message of custom loader, developer needs to update `OstSdkMessages.json` file present in loader folder of link:../ios/Loader/OstSdkMessages.json[iOS] and link:../android/app/src/customloader/assets/OstSdkMessages.json[android]
* By default, application doesn't wait for `activate user` and `transaction` workflow completion.
But It can be changed as per application requirements, Please refer link:../ios/Loader/OstMockLoaderManager.swift#L25[for iOS] and link:../android/app/src/customloader/src/OstMockLoaderManager.java#L25[for android] +


= Custom Loader Usage

== Setup

. Application project should have `ost-wallet-sdk-android` dependency.
. Copy `customloader` directory in Application project `src` directory.
. Define `customloader` resources and assets directory in application build.gradle.
+
----
android {
     sourceSets {
             main.java.srcDirs += 'src/customloader/src'
             main.assets.srcDirs += 'src/customloader/assets'
             main.res.srcDirs += 'src/customloader/res'
     }
}
----

. Add resource import statements in `GIFView.java` and `OstMockLoaderFragment.java`
+
----
import <Your application pacakge name>.R
----

. Set LoaderManager of Custom loader in your application onCreate method
+
[source,java]
----
public class App extends Application {
 @Override
 public void onCreate() {
     super.onCreate();
     /* Add below line in you application onCreate */
     OstWalletUI.setLoaderManager(customloader.src.OstMockLoaderManager.getInstance());
 }
}
----

After performing above steps, you are good to go with custom loader.

== Customize Loader

You can customize icons and text for custom loader as per application need.

=== 1. Loader gif:

To modfiy loader, Add your `.gif` file and rename as `ost_progress_image.gif`.
After that, replace it with `src/customloader/res/drawable/ost_progress_image.gif` +

=== 2. Success and Failure Icon:

To modify Icons, open `src/customloader/res/drawable/` and replace `ost_success_icon.png` and `ost_failure_icon` with your application icons.

=== 3. Modify success message:

Developer can modify success message by modifying `SUCCESS_MESSAGE` value in `src/customloader/assets/OstSdkMessages.json` file

=== 4. Modify loader text:

To modify loader text, update language for key `text` under `initial_loader`, `loader` and `acknowledge` in ost_content_config.json + ost_content_config is a file, which you set for `setContentConfig` function.
